version: '3.7'

services:
  front:
    build: ./frontend
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    ports:
      - ${FRONT_PORT}:3000
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1028M
  
  api:
    build: ./backend
    volumes:
      - ./backend:/app:cached
    ports:
      - ${BACK_PORT}:8000
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1028M
