version: '3.8'

services:
  front:
    container_name: frontend
    build: ./frontend
    user: node
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    ports:
      - ${FRONT_PORT}:3000
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1028M
  
  api:
    container_name: API
    build: ./backend
    volumes:
      - ./backend:/app:cached
    ports:
      - ${BACK_PORT}:8000
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1028M
  bd-mongo:
    container_name: mongodb
    image: mongo:4.2
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./volumes/mongodb:/data/bd-mongo
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge
